import { pool } from "@workspace/db";
import { logger } from "./logger";

const statements = [
  `CREATE TABLE IF NOT EXISTS users (
    id serial PRIMARY KEY,
    username text NOT NULL DEFAULT '',
    password_hash text NOT NULL DEFAULT '',
    full_name text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT 'student',
    status text NOT NULL DEFAULT 'pending',
    phone text,
    subject text,
    additional_exams text[] NOT NULL DEFAULT '{}',
    review_bucket_dismissed_question_ids integer[] NOT NULL DEFAULT '{}',
    avatar_url text,
    onboarding_complete boolean NOT NULL DEFAULT false,
    student_profile_data text,
    must_change_password boolean NOT NULL DEFAULT false,
    last_password_reset_email_at timestamptz,
    reviewed_by_id integer,
    reviewed_at timestamptz,
    approved_by_id integer,
    approved_at timestamptz,
    rejection_reason text,
    pending_review_started_at timestamptz,
    pending_review_escalated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique ON users(username)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users(email)`,
  `CREATE TABLE IF NOT EXISTS classes (
    id serial PRIMARY KEY,
    title text NOT NULL,
    description text,
    subject text NOT NULL DEFAULT '',
    workflow_type text NOT NULL DEFAULT 'class',
    admin_id integer NOT NULL REFERENCES users(id),
    assigned_teacher_ids integer[] NOT NULL DEFAULT '{}',
    planner_id integer REFERENCES users(id),
    status text NOT NULL DEFAULT 'scheduled',
    scheduled_at timestamptz,
    started_at timestamptz,
    ended_at timestamptz,
    weekly_target_questions integer,
    weekly_target_deadline timestamptz,
    is_locked boolean NOT NULL DEFAULT false,
    max_students integer,
    meeting_link text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS subjects (
    id serial PRIMARY KEY,
    class_id integer NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    teacher_id integer REFERENCES users(id) ON DELETE SET NULL,
    title text NOT NULL,
    description text,
    "order" integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS chapters (
    id serial PRIMARY KEY,
    subject_id integer NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    target_questions integer NOT NULL DEFAULT 0,
    "order" integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS tests (
    id serial PRIMARY KEY,
    class_id integer REFERENCES classes(id) ON DELETE CASCADE,
    chapter_id integer REFERENCES chapters(id) ON DELETE SET NULL,
    title text NOT NULL,
    description text,
    exam_type text NOT NULL DEFAULT 'custom',
    exam_header text,
    exam_subheader text,
    instructions text,
    exam_config text,
    duration_minutes integer NOT NULL DEFAULT 30,
    passing_score integer,
    default_positive_marks real NOT NULL DEFAULT 1,
    default_negative_marks real NOT NULL DEFAULT 0,
    is_published boolean NOT NULL DEFAULT false,
    sync_question_bank_on_publish boolean NOT NULL DEFAULT true,
    is_student_visible boolean NOT NULL DEFAULT true,
    scheduled_at timestamptz,
    created_by integer REFERENCES users(id),
    created_at timestamptz DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS test_sections (
    id serial PRIMARY KEY,
    test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    subject_label text,
    question_count integer,
    marks_per_question real,
    negative_marks real,
    meta text,
    "order" integer NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS test_questions (
    id serial PRIMARY KEY,
    test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    section_id integer REFERENCES test_sections(id) ON DELETE SET NULL,
    question text NOT NULL,
    question_type text NOT NULL DEFAULT 'mcq',
    question_code text,
    source_type text NOT NULL DEFAULT 'manual',
    subject_label text,
    options text NOT NULL DEFAULT '[]',
    option_images text,
    correct_answer real NOT NULL DEFAULT 0,
    correct_answer_multi text,
    correct_answer_min real,
    correct_answer_max real,
    points integer NOT NULL DEFAULT 1,
    negative_marks real NOT NULL DEFAULT 0,
    meta text,
    solution_text text,
    solution_image_data text,
    ai_solution_text text,
    "order" integer NOT NULL DEFAULT 0,
    image_data text
  )`,
  `CREATE TABLE IF NOT EXISTS test_submissions (
    id serial PRIMARY KEY,
    test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    student_id integer NOT NULL REFERENCES users(id),
    answers text NOT NULL,
    question_timings text,
    flagged_questions text,
    visited_question_ids text,
    review_question_ids text,
    interaction_log text,
    score real NOT NULL DEFAULT 0,
    total_points integer NOT NULL DEFAULT 0,
    percentage real NOT NULL DEFAULT 0,
    passed boolean NOT NULL DEFAULT false,
    submitted_at timestamptz DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS question_bank_questions (
    id serial PRIMARY KEY,
    class_id integer NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    chapter_id integer NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    question text NOT NULL,
    question_type text NOT NULL DEFAULT 'mcq',
    options text NOT NULL DEFAULT '[]',
    option_images text,
    correct_answer integer,
    correct_answer_multi text,
    correct_answer_min integer,
    correct_answer_max integer,
    answer text,
    explanation text,
    topic_tag text,
    difficulty text NOT NULL DEFAULT 'medium',
    points integer NOT NULL DEFAULT 1,
    "order" integer NOT NULL DEFAULT 0,
    image_data text,
    source_test_id integer,
    source_test_question_id integer,
    created_by integer REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS test_question_bank_links (
    id serial PRIMARY KEY,
    test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    test_question_id integer NOT NULL REFERENCES test_questions(id) ON DELETE CASCADE,
    question_bank_question_id integer NOT NULL REFERENCES question_bank_questions(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS test_question_bank_links_test_question_unique
    ON test_question_bank_links(test_question_id)`,
  `CREATE TABLE IF NOT EXISTS test_question_reports (
    id serial PRIMARY KEY,
    test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES test_questions(id) ON DELETE CASCADE,
    reported_by integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    teacher_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reason text NOT NULL,
    status text NOT NULL DEFAULT 'open',
    teacher_note text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS question_bank_reports (
    id serial PRIMARY KEY,
    question_id integer NOT NULL REFERENCES question_bank_questions(id) ON DELETE CASCADE,
    class_id integer NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    chapter_id integer NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    reported_by integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    teacher_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reason text,
    status text NOT NULL DEFAULT 'open',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS question_bank_saved_questions (
    id serial PRIMARY KEY,
    question_id integer NOT NULL REFERENCES question_bank_questions(id) ON DELETE CASCADE,
    student_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS question_bank_question_progress (
    id serial PRIMARY KEY,
    question_id integer NOT NULL REFERENCES question_bank_questions(id) ON DELETE CASCADE,
    student_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    class_id integer NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    chapter_id integer NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    attempt_count integer NOT NULL DEFAULT 0,
    correct_count integer NOT NULL DEFAULT 0,
    incorrect_count integer NOT NULL DEFAULT 0,
    last_answer text,
    last_is_correct boolean NOT NULL DEFAULT false,
    first_attempted_at timestamptz NOT NULL DEFAULT now(),
    last_attempted_at timestamptz NOT NULL DEFAULT now(),
    solved_at timestamptz
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS question_bank_question_progress_unique
    ON question_bank_question_progress(question_id, student_id)`,
  `CREATE TABLE IF NOT EXISTS exam_templates (
    id serial PRIMARY KEY,
    key text NOT NULL,
    name text NOT NULL,
    description text,
    exam_header text,
    exam_subheader text,
    instructions text,
    duration_minutes integer NOT NULL DEFAULT 180,
    passing_score integer,
    default_positive_marks real NOT NULL DEFAULT 1,
    default_negative_marks real NOT NULL DEFAULT 0,
    sections text NOT NULL DEFAULT '[]',
    is_system boolean NOT NULL DEFAULT false,
    is_locked boolean NOT NULL DEFAULT false,
    show_in_registration boolean NOT NULL DEFAULT true,
    created_by integer REFERENCES users(id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS enrollments (
    id serial PRIMARY KEY,
    student_id integer NOT NULL REFERENCES users(id),
    class_id integer NOT NULL REFERENCES classes(id),
    enrolled_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS unique_enrollment ON enrollments(student_id, class_id)`,
  `CREATE TABLE IF NOT EXISTS whiteboards (
    id serial PRIMARY KEY,
    class_id integer NOT NULL UNIQUE REFERENCES classes(id),
    data text NOT NULL DEFAULT '[]',
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS feedback (
    id serial PRIMARY KEY,
    class_id integer NOT NULL REFERENCES classes(id),
    student_id integer NOT NULL REFERENCES users(id),
    rating integer NOT NULL,
    comment text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS support_tickets (
    id serial PRIMARY KEY,
    student_id integer NOT NULL REFERENCES users(id),
    subject text NOT NULL,
    message text NOT NULL,
    image_data text,
    status text NOT NULL DEFAULT 'open',
    admin_response text,
    responded_by integer REFERENCES users(id),
    deadline timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS support_ticket_messages (
    id serial PRIMARY KEY,
    ticket_id integer NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
    sender_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender_name text NOT NULL,
    sender_role text NOT NULL,
    message text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS community_posts (
    id serial PRIMARY KEY,
    author_id integer NOT NULL REFERENCES users(id),
    content text NOT NULL,
    image_url text,
    parent_id integer,
    is_pinned boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS assignments (
    id serial PRIMARY KEY,
    class_id integer NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    created_by integer NOT NULL REFERENCES users(id),
    title text NOT NULL,
    description text,
    due_at timestamptz,
    max_marks integer DEFAULT 100,
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS assignment_submissions (
    id serial PRIMARY KEY,
    assignment_id integer NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    student_id integer NOT NULL REFERENCES users(id),
    file_name text,
    file_data text,
    file_type text,
    comment text,
    grade integer,
    feedback text,
    graded_by integer REFERENCES users(id),
    submitted_at timestamptz NOT NULL DEFAULT now(),
    graded_at timestamptz
  )`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id serial PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type text NOT NULL,
    title text NOT NULL,
    message text,
    link text,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS notification_preferences (
    id serial PRIMARY KEY,
    user_id integer NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    assignment boolean NOT NULL DEFAULT true,
    grade boolean NOT NULL DEFAULT true,
    test boolean NOT NULL DEFAULT true,
    class boolean NOT NULL DEFAULT true,
    system boolean NOT NULL DEFAULT true,
    community boolean NOT NULL DEFAULT true,
    digest boolean NOT NULL DEFAULT true,
    weekly_digest boolean NOT NULL DEFAULT true,
    last_digest_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS attendance (
    id serial PRIMARY KEY,
    class_id integer NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    student_id integer NOT NULL REFERENCES users(id),
    date text NOT NULL,
    status text NOT NULL,
    marked_by integer REFERENCES users(id),
    note text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS direct_messages (
    id serial PRIMARY KEY,
    sender_id integer NOT NULL REFERENCES users(id),
    receiver_id integer NOT NULL REFERENCES users(id),
    content text NOT NULL,
    is_reported boolean NOT NULL DEFAULT false,
    report_reason text,
    reported_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS lecture_plans (
    id serial PRIMARY KEY,
    title text NOT NULL,
    subject text NOT NULL,
    description text,
    scheduled_at timestamptz NOT NULL,
    teacher_id integer NOT NULL REFERENCES users(id),
    planner_id integer NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS lectures (
    id serial PRIMARY KEY,
    subject_id integer NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    chapter_id integer REFERENCES chapters(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    video_url text,
    "order" integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS lecture_enrollments (
    id serial PRIMARY KEY,
    student_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lecture_id integer NOT NULL REFERENCES lectures(id) ON DELETE CASCADE,
    enrolled_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS unique_lecture_enrollment
    ON lecture_enrollments(student_id, lecture_id)`,
  `CREATE TABLE IF NOT EXISTS class_materials (
    id serial PRIMARY KEY,
    class_id integer NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    file_data text NOT NULL,
    mime_type varchar(100) NOT NULL DEFAULT 'application/pdf',
    uploaded_at timestamptz DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS contact_submissions (
    id serial PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    subject text NOT NULL,
    message text NOT NULL,
    status text NOT NULL DEFAULT 'new',
    reviewed_by integer REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS platform_settings (
    id integer PRIMARY KEY DEFAULT 1,
    student_review_email_enabled boolean NOT NULL DEFAULT true,
    student_review_email_actions_enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS password_reset_requests (
    id serial PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    requested_username text NOT NULL,
    requested_email text NOT NULL,
    status text NOT NULL DEFAULT 'open',
    resolved_by integer REFERENCES users(id),
    resolution_note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS email_provider_configs (
    id serial PRIMARY KEY,
    provider_key text NOT NULL,
    provider_name text NOT NULL,
    provider_type text NOT NULL DEFAULT 'brevo',
    api_key text NOT NULL,
    sender_email text NOT NULL,
    sender_name text NOT NULL DEFAULT 'Rank Pulse',
    reply_to_email text,
    reply_to_name text,
    daily_limit integer NOT NULL DEFAULT 300,
    daily_soft_limit integer NOT NULL DEFAULT 250,
    is_active boolean NOT NULL DEFAULT true,
    created_by_id integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS email_provider_configs_provider_key_unique
    ON email_provider_configs(provider_key)`,
  `CREATE TABLE IF NOT EXISTS email_provider_daily_usage (
    id serial PRIMARY KEY,
    provider_key text NOT NULL,
    usage_date text NOT NULL,
    sent_count integer NOT NULL DEFAULT 0,
    last_sent_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS email_provider_daily_usage_provider_date_unique
    ON email_provider_daily_usage(provider_key, usage_date)`,
  `CREATE TABLE IF NOT EXISTS email_send_logs (
    id serial PRIMARY KEY,
    provider_key text NOT NULL,
    provider_name text NOT NULL,
    provider_source text NOT NULL DEFAULT 'database',
    sender_email text NOT NULL,
    recipient_email text NOT NULL,
    subject text NOT NULL,
    message_type text NOT NULL DEFAULT 'transactional',
    status text NOT NULL DEFAULT 'sent',
    error_message text,
    metadata text,
    sent_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS user_activity_logs (
    id serial PRIMARY KEY,
    user_id integer NOT NULL,
    action text NOT NULL,
    page text,
    detail text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS user_sessions (
    id serial PRIMARY KEY,
    user_id integer NOT NULL,
    session_token text NOT NULL,
    ip_address text,
    location_label text,
    browser_name text,
    device_type text,
    user_agent text,
    started_at timestamptz NOT NULL DEFAULT now(),
    last_active_at timestamptz NOT NULL DEFAULT now(),
    ended_at timestamptz,
    total_seconds integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true
  )`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS username text NOT NULL DEFAULT ''`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash text NOT NULL DEFAULT ''`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name text NOT NULL DEFAULT ''`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT ''`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'student'`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending'`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS phone text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS subject text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS additional_exams text[] NOT NULL DEFAULT '{}'`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS review_bucket_dismissed_question_ids integer[] NOT NULL DEFAULT '{}'`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_complete boolean NOT NULL DEFAULT false`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS student_profile_data text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS last_password_reset_email_at timestamptz`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS reviewed_by_id integer`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS reviewed_at timestamptz`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_by_id integer`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at timestamptz`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS rejection_reason text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_review_started_at timestamptz`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_review_escalated_at timestamptz`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now()`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now()`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS exam_header text`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS exam_subheader text`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS instructions text`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS exam_config text`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS default_positive_marks real NOT NULL DEFAULT 1`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS default_negative_marks real NOT NULL DEFAULT 0`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS sync_question_bank_on_publish boolean NOT NULL DEFAULT true`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS is_student_visible boolean NOT NULL DEFAULT true`,
  `ALTER TABLE tests ADD COLUMN IF NOT EXISTS scheduled_at timestamptz`,
  `ALTER TABLE classes ADD COLUMN IF NOT EXISTS is_locked boolean NOT NULL DEFAULT false`,
  `CREATE TABLE IF NOT EXISTS test_sections (
    id serial PRIMARY KEY,
    test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    subject_label text,
    question_count integer,
    marks_per_question real,
    negative_marks real,
    meta text,
    "order" integer NOT NULL DEFAULT 0
  )`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS section_id integer REFERENCES test_sections(id) ON DELETE SET NULL`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS question_type text NOT NULL DEFAULT 'mcq'`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS question_code text`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS source_type text NOT NULL DEFAULT 'manual'`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS subject_label text`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS option_images text`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS correct_answer_multi text`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS correct_answer_min real`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS correct_answer_max real`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS negative_marks real NOT NULL DEFAULT 0`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS meta text`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS solution_text text`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS solution_image_data text`,
  `ALTER TABLE test_questions ADD COLUMN IF NOT EXISTS ai_solution_text text`,
  `CREATE TABLE IF NOT EXISTS test_question_bank_links (
    id serial PRIMARY KEY,
    test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    test_question_id integer NOT NULL REFERENCES test_questions(id) ON DELETE CASCADE,
    question_bank_question_id integer NOT NULL REFERENCES question_bank_questions(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS test_question_bank_links_test_question_unique
    ON test_question_bank_links(test_question_id)`,
  `CREATE TABLE IF NOT EXISTS exam_templates (
    id serial PRIMARY KEY,
    key text NOT NULL,
    name text NOT NULL,
    description text
  )`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS exam_header text`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS exam_subheader text`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS instructions text`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS duration_minutes integer NOT NULL DEFAULT 180`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS passing_score integer`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS default_positive_marks real NOT NULL DEFAULT 1`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS default_negative_marks real NOT NULL DEFAULT 0`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS sections text NOT NULL DEFAULT '[]'`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS is_system boolean NOT NULL DEFAULT false`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS is_locked boolean NOT NULL DEFAULT false`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS show_in_registration boolean NOT NULL DEFAULT true`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS created_by integer REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE exam_templates ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now()`,
];

export async function ensureRuntimeSchema() {
  for (const statement of statements) {
    await pool.query(statement);
  }
  logger.info("Runtime schema check completed");
}
