import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import classesRouter from "./classes";
import whiteboardRouter from "./whiteboard";
import dashboardRouter from "./dashboard";
import { feedbackRouter } from "./feedback";
import { supportRouter } from "./support";
import { communityRouter } from "./community";
import { financeRouter } from "./finance";
import { subjectsRouter } from "./subjects";
import { materialsRouter } from "./materials";
import { testsRouter } from "./tests";
import activityRouter from "./activity";
import assignmentsRouter from "./assignments";
import notificationsRouter from "./notifications";
import attendanceRouter from "./attendance";
import leaderboardRouter from "./leaderboard";
import analyticsRouter from "./analytics";
import { teacherPerformanceRouter } from "./teacherPerformance";
import { dmRouter } from "./dm";
import { paymentsRouter } from "./payments";
import { lecturePlansRouter } from "./lecturePlans";
import { questionBankRouter } from "./questionBank";
import { plannerRouter } from "./planner";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(classesRouter);
router.use(whiteboardRouter);
router.use(dashboardRouter);
router.use("/feedback", feedbackRouter);
router.use("/support", supportRouter);
router.use(communityRouter);
router.use(financeRouter);
router.use(subjectsRouter);
router.use(materialsRouter);
router.use(testsRouter);
router.use("/activity", activityRouter);
router.use(assignmentsRouter);
router.use(notificationsRouter);
router.use(attendanceRouter);
router.use(leaderboardRouter);
router.use(analyticsRouter);
router.use(teacherPerformanceRouter);
router.use(dmRouter);
router.use(paymentsRouter);
router.use(lecturePlansRouter);
router.use(questionBankRouter);
router.use(plannerRouter);

export default router;
